### ISSUE TITLE
Changes to NARCCAP

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#107]
OK, got some requests for changes to the NARCCAP layer(s) from NYSERDA.  

1. Add monthly NARCCAP layers in addition to the seasonal and annual.  These monthly layers are already available from ACIS, according to Art.  The purpose of this is to allow the NARCCAP to be more directly comparable to the PRISM (historical data) which is presented on a monthly basis.  (Both Art and I argued against this from a science point of view but NYSERDA did not budge.  They pay the bills, so...)

2. Break out the four NARCCAP data products (avg temp, max temp, min temp, precip) into separate layers in the layer tree.  I suggested this in the hopes that it would reduce the number of sub-layers (permutations) that would need to be loaded into d3, given that we are adding 12 new sets of layers (months) for each product (variable).  Does this in fact help?    

3. We had a debate about the yearly resolution of the NARCCAP projections and whether it would be more useful and efficient l to provide fewer data points in time.  I brought this up because it might allow us to reduce the dimensionality of the data somewhat.  We agreed that 10 year averages (2039-2048, 2049-2058, etc.) would be a reasonable way of presenting the data.  

Question is: just where does the 10 year averaging of the NARCCAP occur?  Does ACIS pre-cook this data and serve it to us?  Or do we still harvest the annual data and do the averaging in d3?  I would rather have ACIS take care of it for a number of reasons.  Art is going to talk to Bill Noon about this, and so I'm asking you guys.  If its too much time or will cause unacceptable lags in our map performance, tell me.  Either way we'll have to make UI tweaks.  Thoughts?

**Comment by caryfitzhugh** [comment]
Hey Colin,

Monthly NARCCAP layers is possible, they are separate files to download. Their performance will be comparable to the other layers. It would be a 30 min change I think, just to add those new season names in and quickly test.

Splitting into multiple layers is fine - I don't think it saves much on performance - but at the very least we should split the precipitation layer out from narccap -- since in climaid it will be a separate layer as well?
I think keeping them similarly laid out would be good? (yes?)

We can do 10 year averages, the data that Art is giving us is year-by-year, (https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/narccap/state/mint_Jan)   so we can avg things into 10 year buckets pretty easily.  The performance shouldn't change.

**Comment by colinbeier** [comment]
Sounds good! Let's move ahead with these changes this week, if possible. Thanks!

Colin Beier
SUNY ESF

On Jan 11, 2016 1:06 PM, Cary FitzHugh <notifications@github.com> wrote:

Hey Colin,

Monthly NARCCAP layers is possible, they are separate files to download. Their performance will be comparable to the other layers. It would be a 30 min change I think, just to add those new season names in and quickly test.

Splitting into multiple layers is fine - I don't think it saves much on performance - but at the very least we should split the precipitation layer out from narccap -- since in climaid it will be a separate layer as well?
I think keeping them similarly laid out would be good? (yes?)

We can do 10 year averages, the data that Art is giving us is year-by-year, (https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/narccap/state/mint_Jan) so we can avg things into 10 year buckets pretty easily. The performance shouldn't change.

**Comment by caryfitzhugh** [comment]
hey colin. is the narccap precip a delta or a projected value?
inches? cm?   etc?

**Comment by colinbeier** [comment]
projected precipitation in cm.
