### ISSUE TITLE
Map sharing functions

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#116]
Can you guys explain the current function(s) we have for map sharing?  Do these serve anybody's needs if they don't already have a web map?   Could, for example, somebody send the map they created by email or share via social media?  

Here is the comment from NYSERDA: 
•	Is it possible to create a save a map(s) feature, similar to the one on the data tool?  

Not sure that 'save' is the same as 'share' and I am trying to clarify this comment.  But it would be good to know what other options, if any, are available here.

**Comment by caryfitzhugh** [comment]
It's currently a simple copy of the current map state. In JSON.  And you can paste that blob into a different map, and it will load and show the same stuff (position/ zoom /etc).  I went this far because this is the "hard" part of the problem, can you save  and reload the map's state?  Yes we can. I didn't go farther b/c it depends on what people want.

You could email that JSON string to someone, and they would paste it into the Import field.  It's a bit wonky though - because it could be a large string!

There is more we could do with this to create a sharable link.

* adding an API to save the map data to our server (which one?) and get back a token (I think Steve already built this)
* getting the current page URL, and adding a token on it ?nyccsc_map_state=XXXXXXXX
* when our page is loaded in an iframe, we try to read the token, load the data from the server, and update the map

The data viewer just needs to load one piece of data (the path) - so it can simply use that.  We on the other hand, have many many parameters and fields, and our JSON blob can easily be too long for the URL.  So we have to save it to a token, and pass the token around.

Anyway - a few hours is my estimate. 4? 3?  something like that.
Assuming that @sasignell 's loading / saving code is still in workable condition.

I tested on the cornell site and we do have access to the URL bar, so we can do this.

**Comment by colinbeier** [comment]
What about ways to share a static map image with legend?  Something like a screen cap.   Maybe that is what print is for?  This reminds me that the print function doesn't work too great, at least on my laptop.  It only grabs part of the screen.  

I think the idea you describe using tokens sounds great.  let me run it up the flagpole with Lisa and NYSERDA before we decide to proceed.

**Comment by caryfitzhugh** [comment]
Print can be tweaked with CSS -- we should be able to do better.
Will await the decision!

**Comment by caryfitzhugh** [comment]
@colinbeier what was the decision on the token / sharing? Should we implement?

**Comment by caryfitzhugh** [comment]
duplicated in #125

**Comment by colinbeier** [comment]
Brought it up a while ago, heard nothing.  I will ask Lisa again.  

Is a token needed so the map remembers the visitor and loads up again as it was saved / left?  If so, I don't think we need that kind of feature... just something that cleanly outputs, with legend and logo, a nice pdf or high-res png image. Can that kind of thing be done without a token?

**Comment by caryfitzhugh** [comment]
Yes.  Clean printing is just some css.

Well should remove the share button then I would think....

**Comment by colinbeier** [comment]
No need to remove button or current sharing features, just add clean printing to those options

Colin Beier
SUNY ESF

On Feb 8, 2016 7:31 PM, Cary FitzHugh <notifications@github.com> wrote:
Yes. Clean printing is just some css.

Well should remove the share button then I would think....
