### ISSUE TITLE
Rare Plants & Animals (DEC ERM)

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#140]
Rare Plants & Animals (DEC ERM)
maps.naturalresourcenavigator.org
These are the calls to the service for species hexagons
ArcGIS page
Statewide Data:
allspp_nonsp_download.zip

**Comment by caryfitzhugh** [comment]
@sasignell this didn't make sense to me.  What was your plan for pulling these in?

**Comment by caryfitzhugh** [comment]
This looks like we can do a WMS layer against their ArcGIS server.

Working on pulling in the different species now.

**Comment by caryfitzhugh** [comment]
ok. there are a LOT of species. And it bogs the browser down quite a bit.

We could combine them (if we wanted) in some fashion.  Like group similar animals (I is all a WMS call, so I thik they would be able to support multiple species in one graph (but since we don't support the GFI call, its harder)...  

@colinbeier this will require some input from you.  I can cull the list of 950+ items down to any subset if we want, just need to know what we want. 
I think < 100 is probably reasonable for speed, but we'd have to fiddle.

**Comment by caryfitzhugh** [comment]
Not closed just yet :)

**Comment by caryfitzhugh** [comment]
this is on gh-pages now.

**Comment by colinbeier** [comment]
OK will look at it tonight after dinner / bathtime :)

Colin Beier
SUNY ESF

On Feb 29, 2016 5:05 PM, Cary FitzHugh <notifications@github.com> wrote:

ok. there are a LOT of species. And it bogs the browser down quite a bit.

We could combine them (if we wanted) in some fashion. Like group similar animals (I is all a WMS call, so I thik they would be able to support multiple species in one graph (but since we don't support the GFI call, its harder)...

@colinbeier<https://github.com/colinbeier> this will require some input from you. I can cull the list of 950+ items down to any subset if we want, just need to know what we want.
I think < 100 is probably reasonable for speed, but we'd have to fiddle.

**Comment by colinbeier** [comment]
on the natural resource navigator site, in the list of layers, in the Species folder, the Predicted Species Richness for Rare Species is what we're looking for.  3 datasets for each group of critters: predicted future, predicted current, predicted change. 9 groups of critters (all, animal, plant, vert, invert, bird, aerial insect, fed listed, nys listed).  now we could include all 27 layers here with two toggles (dataset x critter group) but I'm not sure that's necessary.  maybe just the plants, animals, nys listed and fed listed... to start with?

**Comment by caryfitzhugh** [comment]
Hey Colin,

I'm sorry, but I don't follow so well what you are describing :(  
If you could give me some screenshots of how you are finding this set of 3 and 9 etc.  

I tried to figure it out and did this, but I find 33 animals.

If I click on future species, and rare species like so:
![image](https://cloud.githubusercontent.com/assets/445848/13430499/48464a4a-df93-11e5-993c-999804bc972c.png)

I get these 33 animals:
* Bald Eagle (Haliaeetus leucocephalus)	Bird
* Blackchin Shiner (Notropis heterodon)	Fish
* Bog Turtle (Glyptemys muhlenbergii)	Reptile
* Cerulean Warbler (Dendroica cerulea)	Bird
* Common Loon (Gavia immer)	Bird
* Copperhead (Agkistrodon contortrix)	Reptile
* Drummond's Rock-cress (Boechera stricta)	Vascular Plant
* Eastern Ratsnake (Elaphe obsoleta)	Reptile
* Eastern Ribbonsnake (Thamnophis sauritus)	Reptile
* Eastern Small-footed Myotis (Myotis leibii)	Mammal
* Eastern/Woodland Box Turtle (Terrapene carolina carolina)	Reptile
* Extra-striped Snaketail (Ophiogomphus anomalus)	Odonate
* Five-lined Skink (Eumeces fasciatus)	Reptile
* Four-toed Salamander (Hemidactylium scutatum)	Amphibian
* Golden Eagle (Aquila chrysaetos)	Bird
* Green Rock-cress (Boechera missouriensis)	Vascular Plant
* Jefferson Salamander Complex (Ambystoma jeffersonianum x laterale)	Amphibian
* Least Bittern (Ixobrychus exilis)	Bird
* Livid Sedge (Carex livida)	Vascular Plant
* Longtail/Long-tailed Salamander (Eurycea longicauda)	Amphibian
* Marbled Salamander (Ambystoma opacum)	Amphibian
* Northern Black Racer (Coluber constrictor constrictor )	Reptile
* Northern Harrier (Circus cyaneus)	Bird
* Peregrine Falcon (Falco peregrinus)	Bird
* Pied-billed Grebe (Podilymbus podiceps)	Bird
* Rock-cress (Draba arabisans)	Vascular Plant
* Smooth Cliff Brake (Pellaea glabella ssp. glabella)	Vascular Plant
* Southern Twayblade (Listera australis)	Vascular Plant
* Spotted Pondweed (Potamogeton pulcher)	Vascular Plant
* Spotted Turtle (Clemmys guttata)	Reptile
* Timber Rattlesnake (Crotalus horridus)	Reptile
* Water Milfoil (Myriophyllum alterniflorum)	Vascular Plant
*Wood Turtle (Glyptemys insculpta)	Reptile

**Comment by colinbeier** [comment]
Not using the Species Explorer, but going in through the directory you get when you hit Map Layers.  There is one folder - Habitat Climate and Reference Data.  Open that.  Then hit the Species folder (at the bottom of the list), and three subdirectories down is the Predicted Species Richness for Rare Species.  In there are three sets of layers (future, current, change), each set covers 9 groups of critters.

**Comment by caryfitzhugh** [comment]
@colinbeier ahh. got it. ok.

I'll go with two controls:
![image](https://cloud.githubusercontent.com/assets/445848/13474076/5f93b046-e08a-11e5-8786-5b28cd6aad41.png)

**Comment by caryfitzhugh** [comment]
this is deployed on gh-pages.

**Comment by colinbeier** [comment]
i like the layout of the legend toggles, but the layer (data) is not mapping... just spins and spins.

**Comment by caryfitzhugh** [comment]
Hrm....
