### ISSUE TITLE
Creating ag land cover layers from NY LU/LC layer 

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#149]
For the next (not current) release...Our agriculture and pasture layers are pretty terrible on their own, for that folder... they are carry overs from early on. 

I think we could keep them (or dump them) but they should be renamed 'Global Croplands' and 'Global Pastures' so folks are prepared for the very coarse resolution of the data.  

Since the NY LU/LC layer is a wms from the natresource navigator site, could we filter it into a few stand alone layers that shows only one or a few of the land classes, say: 

- one for pasture & hay
- one for cultivated crops plus new agriculture
- one that includes all low, medium and high intensity development

It would be neat if each of these layers would have a toggle for selecting 2011 or 2050 as the time period. 

We can keep the same symbology (color) in these layers, that way if someone lights up the entire LULC layer too, everything will match.  

Let me know what you think.

**Comment by caryfitzhugh** [comment]
I looked on the WMS page
http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_toolkit/MapServer

And saw the layer #208 (lulc 2050) and it has no way to split it apart into those sublayers. I think they packaged it up and we can't split those apart.

@sasignell would know, but it may be pretty easy to have naturalresourcenavigator modify their geoserver so that you can grab those individual sub-layers.  Because then we'd be able to do what you want pretty easily.

As of right now - the lulc layers are all glommed together.

**Comment by sasignell** [comment]
there is a [query tool](http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_toolkit/MapServer/209/query) but I don't know how it works...

**Comment by caryfitzhugh** [comment]
@colinbeier I think this one is DOA unless they change their server to expose the different layers to us.

**Comment by colinbeier** [comment]
OK close it for now, will revisit if possible / necessary...

Colin Beier
SUNY ESF

On Mar 16, 2016 12:02 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> I think this one is DOA unless they change their server to expose the different layers to us.
