### ISSUE TITLE
Need Columbia dataset at a minimum.  Dewberry, if possible.

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#171]

**Comment by sasignell** [comment]
added the Nyserda_slr layer... it would be nice to have sliders here, but the increments for both rise and return are irregular which our sliders can't currently accommodate.  We could make the rise a slider if we only use the whole foot increments.

**Comment by colinbeier** [comment]
The drop downs are OK.  A few questions:

1. Does the data really only cover the lower Hudson, and none of NYC or LI?  

2. It is VERY slow to load, even when I zoom in tight.  Can we do anything to speed it up?  

3. Does the Columbia site have metadata and/or a narrative description we can grab?  I'm not sure what these data mean.  Are there any other variables available?  

4. The GetInfo button is there but when I click on the map I'm not getting anything to return.  It would be AWESOME to have this enable for both SLR datasets, but not sure if that's possible?  I think the WMS is just an image, and is not associated with a real data value per pixel, right?

**Comment by caryfitzhugh** [comment]
@colinbeier 

1) I have no idea - ask @sasignell  :)

2) the load speed is because the nyserda server is a dog.  We cache it in cloudfront, but the initial request for tiles is quite laggy... not much to be done about that except tell them to put it on a bigger server....

3)  Couldn't find much... ask @sasignell 

4)   GetInfo requests are going to their server, but it is returning nada.  So - that may be a geoserver config on their end? No idea.

**Comment by caryfitzhugh** [comment]
@colinbeier 
hey bro, 
what's the dealio 
with this issue-o?
close-io?

**Comment by colinbeier** [comment]
its in there, its slow, GFI don't work, but we know why.  but its in there.
