### ISSUE TITLE
attirubution not pulling from base layers

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#208]
The 'Attribution' div in the lower-right isn't pulling from the attribution in the basemaps.js-- it just says 'Leaflet' all the time

**Comment by caryfitzhugh** [comment]
I shall look at it..

**Comment by caryfitzhugh** [comment]
not sure what was up.  I pulled, saw your changes for new map tiles, and cleaned things up. Added the credits for one, and things looked like they were working.

I'm going to deploy to github gh-pages for @colinbeier to give a thumbs up.

I commented out the OAM layer for now , since it was just borked.  We can re-add it if @sasignell can find a replacement?
