### ISSUE TITLE
Suggestions For Changes to Layer Nomenclature

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#89]
1.       National Land Cover Data Set

a.       I would argue that this should also fall under the Buildings and Transportation sectors, since the map shows residential, commercial, industrial, and transportation regions.

2.       Power Stations

a.       Revised name: “Power Plants” (the original name on the EIA website.)

b.      Revised description: “Power plants, by fuel type.”

3.       GAP Land Cover Dataset

a.       The link in the description (http://biology.usgs.gov/npsveg/nvcs.html) just brings you to the USGS home page.  This link gives more specific information about the classification standard: http://usnvc.org/data-standard/ .

4.       Soils and surficial geology

a.       Is there a more specific link to the data than http://gec.cr.usgs.gov/ ?  A user who wants to get the dataset themselves might have trouble finding it here.  Maybe this could serve as a link for both the data and metadata: https://catalog.data.gov/dataset/terrestrial-ecosystems-topographic-moisture-potential-of-the-conterminous-united-states .

5.       Hurricane Sandy Surge Extent

a.       This layer should probably apply to all sectors, since all were impacted by Hurricane Sandy.  While there’s not much agriculture on the coast there is some, and all the others presumably experienced strong impacts.

6.       Sea Level Rise

a.       I think in one of the content/map calls we had decided to change this name to “Sea Level Rise (NOAA)” so users could immediately know the source.

b.      Sectors: same as above; all sectors are impacted.

c.       Revised description:  “NOAA sea level change model data.”

7.       Superfund sites

a.       I suggest this link for data and metadata: http://sedac.ciesin.columbia.edu/data/set/superfund-atsdr-hazardous-waste-site-ciesin-mod-v2 .

b.      Revised description: The Agency for Toxic Substances and Disease Registry (ATSDR) Hazardous Waste Site Polygon Data with CIESIN Modifications, Version 2 is a database providing georeferenced data for 1,572 National Priorities List (NPL) Superfund sites. 

8.       Anthropogenic Biomes

a.       I suggest this link for data and metadata: http://sedac.ciesin.columbia.edu/data/set/anthromes-anthropogenic-biomes-world-v2-2000 .

b.      Sectors: Ecosystems, Agriculture, Buildings

9.       Max. Temp. 1980-2014

a.       Revised name: Maximum Temperature 1980-2014

b.      Applies to all sectors

c.       Maybe avoid the word “polygon” in the description.  A lot of users might not know what a polygon is in this context.  Possible alternative description: Monthly maximum temperature data averaged over the period 1980 to 2014 for three different user-selected spatial units in New York State: counties, HUC8 watersheds, and climate divisions.  Users can display means for each month of the year.

10.   Min. Temp. 1980-2014

a.       Revised name: Minimum Temperature 1980-2014

b.      Applies to all sectors

c.       Same comment as above re: “polygon”

11.   Precip. 1980-2014

a.       Revised name: Preciptation 1980-2014

b.      Applies to all sectors

c.       Same comment as above re: “polygon”

12.   NARCCAP data:  I’ll need to take a closer look at this layer next week before commenting

13.   ClimAID projections: I’ll need to take a closer look at this layer next week before commenting

14.   Adirondack Lake Chemistry

a.       Revised name: Adirondack Lake pH and Fish Survey Data

b.      Sectors: Ecosystems and Water Resources

15.   Air Monitoring Stations

a.       I think the folder and sector are switched…folder should be “Climate Data” and sector should be “Public Health.”

16.   Major GHG Emitters

a.       Sector = Energy

b.      Folder is not Public Health

c.       Revised name: Greenhouse Gas Emissions from Large Facilities (the name from the EPA website.)  If it’s too long, you could substitute “GHG” for “Greenhouse Gas.”

d.      The metadata URL  in GitHub is for the Air Monitoring Stations

**Comment by colinbeier** [comment]
More from Ingrid...

Comments on layers:
 
1.       ClimAID Temperature Deltas

a.       Question: I think these are the 2014 updated projections, not the 2011 ones, but please confirm.  I’d like to know so I can associate the data with the appropriate document in VIVO.

a.       Revised name:  ClimAID Temperature Differences or ClimAID Temperature Change (because non-technical audiences might not know what “delta” means)

b.      Revised description: ClimAID modelled temperature change for the years 2020, 2050, and 2080, compared with the baseline period of 1971-2000.  Projections are available for two different emissions scenarios, RCP 4.5 (substantial reductions in GHG emissions before 2100) and RCP 8.5 (increasing GHG emissions with time).

 

2.       NARCCAP Mean Min. Temperature

a.       Revised name: NARCCAP Mean Minimum Temperature

b.      Revised description: NARCCAP projected average minimum temperature summarized by year and county, for the years 2039 to 2069. 

 
3.       Trout Streams

a.       Revised description: New York State Department of Environmental Conservation Water Quality Classifications dataset.  The symbol (T or TS) after any class designation means that designated waters are trout waters (T) or suitable for trout spawning (TS).

b.      Possible additional link to data and metadata: https://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1118 .  The current link goes to a page with administrative info for the Bureau of Water Assessment Management.

c.       Sector:  also Water Resources

 
4.       Biomass Carbon Stock

a.       Revised description: Projected biomass carbon stock (grams of carbon per square meter) in the year 2050 for two different emissions scenarios: IPCC A2 (medium-high emissions) and IPCC B1 (lower emissions). The user can also view modeled biomass carbon stock for the year 2010. Biomass carbon includes carbon stored in above- and below-ground live plant components (such as leaf, branch, stem and root) as well as in standing and down dead woody debris, and fine litter. 

 
5.       FEMA Historic Emergencies

a.       I agree the Public Health folder makes sense, but I suggest it applies to all sectors (in the info pop-up).

 
6.       Social Vulnerability Index

a.       Revised name: Social Vulnerability Index for U.S. Coastal States

**Comment by colinbeier** [comment]
More suggestions from Ingrid on the Taccimo layer (USFS Climate Atlas - Tree Species) 

description of the layer:
 
“Importance Value of thirteen native tree species for three climate conditions: 1) current climate (1961-1990 average); 2) future climate (2071-2100 average) with IPCC scenario B1 (significant conservation and reduction of CO2 emissions); and 3) future climate (2071-2100 average) with IPCC scenario A1FI (high emissions, no modification in current emission trends). Importance Value measures the dominance of a tree species in a forest, based on the relative frequency, density, and basal area of the species.“

Also, can you put units (i.e., “Importance Value”) on the legend? I think it would help users to know what they’re seeing.

**Comment by colinbeier** [comment]
Steve, if you have time this week, it would be great to make progress on this issue.  Thanks!

**Comment by sasignell** [comment]
Ok will do

On Mon, Dec 21, 2015 at 11:48 AM, colinbeier <notifications@github.com>
wrote:

> Steve, if you have time this week, it would be great to make progress on
> this issue. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/89#issuecomment-166356438>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Steve, thanks for making these changes. 

We still need to add units to a variety of our legend information for layers.  Is this a separate issue, or should it be included here?  I reopened this issue but we can close and start a new one.

**Comment by caryfitzhugh** [comment]
we should probably open a new issue and close this one.

**Comment by colinbeier** [comment]
i'm on it... just saw Ingrid's message

**Comment by caryfitzhugh** [comment]
closing this one @colinbeier since you've added the other task (and it has been closed!)
